// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my-message.proto

package br.com.quanto.demoproducer.proto;

public interface MyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:br.com.quanto.demoproducer.proto.MyMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string subject = 3;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 3;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();
}
